### ISSUE TITLE
echronos could be considered as microkernel instead than RTOS?

### ISSUE THREAD

**Issue by Daparrag** [echronos/echronos#52]
# Motivation
Hi guys this is only a simple question about  echronos.

I saw that echronos doesn't have a big difference with a typical microkernel standard such as  L4 family. 
I would like to know if my appreciation is correct or wrong and in case of wrong why? I can assume that echronos could be considered as microkernel instead than RTOS. 

Thanks you. 

sincerely. 
Diego Alejandro.

**Comment by stefangotz** [comment]
Hi Diego,

that's a fair question. There are a few reasons why we do not refer to the eChronos RTOS as a microkernel.

The main consideration is that the primary design priority of the eChronos RTOS is a negligible memory and compute overhead. It deliberately does not implement a lot of features found in the microkernels I am familiar with.

Most importantly, the OS does not isolate itself from tasks or tasks from each other. The assumption here is that the entire application is co-designed and trustworthy.

Technically, this means that there is no generic support for memory protection (although work is being done on that front so that might change).

Similarly, our scheduling relies on a trustworthy application. Although there is a preemptive scheduler, it does not strictly protect the system from tasks that deliberately attempt to hog the CPU.

Furthermore, our APIs are not designed to prevent tasks from maliciously interfering with the OS or other tasks. It is quite possible to use the APIs to access and manipulate the state of the OS and other tasks. Again, this is a deliberate design choice under the assumption of a trustworthy application.

These are all features that are present in the OSs that label themselves microkernels as far as I am aware. Even the word _kernel_ somewhat implies that there is a clear, enforced boundary between kernel and application - which the eChronos RTOS does not provide. That's also why we do not use the term _kernel_ in our documentation.

So while it may be a question of what the exact definition of a microkernel is, I'd say the eChronos RTOS does not fall into that definition. Put another way, if I was involved with the L4 for any other similar microkernel project, I'd find it somewhat preposterous if the eChronos RTOS with its feature set was also considered a microkernel ;-)

Hope that was helpful...

**Comment by Daparrag** [comment]
Hi Stefan gotz

Thanks, you for your reply. I enjoin so much the design of efficient platforms for low and middle processing MCU in special kernel design and RTOS. I consider echronos as a very interesting project.

I'm thinking about virtualization for embedded systems and the possibility to handler more than one RTOS or bare-metal applications in the same MCU concurrently through something which is called hypervisor. 

Thank you for your answer. it was pretty much useful for me.

**Comment by stefangotz** [comment]
Cool, thanks for your interest!
